import { AgentMission } from './types';

export const BASE_MISSIONS: AgentMission[] = [
  {
    id: 'm-yield-01',
    code: 'MSN-01',
    title: 'Aerodrome Slipstream Arbitrage & Yield Route',
    category: 'DeFi',
    difficulty: 'Intermediate',
    rewardXp: 350,
    rewardToken: 'ETH',
    rewardAmount: '0.045',
    description: 'Scan volatile WETH/USDC pools on Base Aerodrome & Uniswap v3 to compute minimal-slippage multi-hop routing.',
    objective: 'Autonomous price discovery, fee tier optimization, and on-chain swap execution simulation.',
    targetContract: '0x4200000000000000000000000000000000000006',
    agentTypeRequired: 'DeFi Yield Sentinel',
    stepsCount: 5,
    estimatedDuration: '18s (Agent Run)',
    verificationMethod: 'On-Chain TX',
    status: 'open',
  },
  {
    id: 'm-audit-02',
    code: 'MSN-02',
    title: 'Base Smart Contract Reentrancy & Bytecode Audit',
    category: 'Security',
    difficulty: 'Expert',
    rewardXp: 500,
    rewardToken: 'USDC',
    rewardAmount: '120.00',
    description: 'Decompile newly deployed unverified bytecode on Base L2, identify suspicious storage slots and execute static reentrancy fuzzing.',
    objective: 'Generate cryptographic audit proof and publish safety score to bAgent Assay registry.',
    targetContract: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    agentTypeRequired: 'EVM Security Auditor',
    stepsCount: 4,
    estimatedDuration: '24s (Agent Run)',
    verificationMethod: 'LLM CoT Proof',
    status: 'open',
  },
  {
    id: 'm-whale-03',
    code: 'MSN-03',
    title: 'Base Whale Swarm & Liquidity Migration Monitor',
    category: 'Intelligence',
    difficulty: 'Autonomous',
    rewardXp: 420,
    rewardToken: 'BAGENT',
    rewardAmount: '750',
    description: 'Track top 100 Base whale wallets bridging from Ethereum L1 and detect sudden LP withdrawals across lending protocols.',
    objective: 'Broadcast automated delta-neutral alert to the bAgent Coordination surface.',
    targetContract: '0x3154Cf16ccdb4C6d922629664174b904d80F2C35',
    agentTypeRequired: 'Whale Tracker AI',
    stepsCount: 5,
    estimatedDuration: '15s (Agent Run)',
    verificationMethod: 'Oracle Signed',
    status: 'open',
  },
  {
    id: 'm-social-04',
    code: 'MSN-04',
    title: 'Farcaster / Base Social Sentiment Ingestion',
    category: 'Social',
    difficulty: 'Beginner',
    rewardXp: 200,
    rewardToken: 'XP',
    rewardAmount: '200',
    description: 'Parse Warpcast trending casts, verify Cast Actions and score builder sentiment for newly launched Base tokens.',
    objective: 'Generate social conviction index and commit hash to Base L2 state.',
    targetContract: '0x00000000fcaf86937e41ba038b4fa40baa4b780a',
    agentTypeRequired: 'Social Intelligence Agent',
    stepsCount: 3,
    estimatedDuration: '12s (Agent Run)',
    verificationMethod: 'Merkle Root',
    status: 'open',
  },
];
